import { useCallback, useState } from 'react';

import { Navigate, useParams } from 'react-router';

import { toast } from 'sonner';
import { v4 as uuidv4 } from 'uuid';

import {
  type DatasourceResultSet,
  type Notebook,
} from '@qwery/domain/entities';
import { NotebookCellData, NotebookUI } from '@qwery/notebook';

import { useWorkspace } from '~/lib/context/workspace-context';
import { useNotebook } from '~/lib/mutations/use-notebook';
import { useRunQuery } from '~/lib/mutations/use-run-query';
import { useRunQueryWithAgent } from '~/lib/mutations/use-run-query-with-agent';
import { useGetDatasourcesByProjectId } from '~/lib/queries/use-get-datasources';
import { useGetNotebook } from '~/lib/queries/use-get-notebook';
import { NOTEBOOK_EVENTS, telemetry } from '@qwery/telemetry';
import { Skeleton } from '@qwery/ui/skeleton';

export default function NotebookPage() {
  const params = useParams();
  const slug = params.slug as string;
  const { repositories, workspace } = useWorkspace();
  const notebookRepository = repositories.notebook;
  const datasourceRepository = repositories.datasource;

  // Store query results by cell ID
  const [cellResults, setCellResults] = useState<
    Map<number, DatasourceResultSet>
  >(new Map());

  // Store query errors by cell ID
  const [cellErrors, setCellErrors] = useState<Map<number, string>>(new Map());

  // Track which cell is currently loading
  const [loadingCellId, setLoadingCellId] = useState<number | null>(null);

  // Load notebook
  const notebook = useGetNotebook(notebookRepository, slug);

  // Load datasources
  const savedDatasources = useGetDatasourcesByProjectId(
    datasourceRepository,
    workspace.projectId as string,
  );

  // Save notebook mutation
  const saveNotebookMutation = useNotebook(
    notebookRepository,
    () => {},
    (error) => {
      console.error(error);
      toast.error(
        `Failed to save notebook: ${error instanceof Error ? error.message : 'Unknown error'}`,
      );
    },
  );

  // Run query mutation
  const runQueryMutation = useRunQuery(
    (result, cellId) => {
      setCellResults((prev) => {
        const next = new Map(prev);
        next.set(cellId, result);
        return next;
      });
      // Clear error on success
      setCellErrors((prev) => {
        const next = new Map(prev);
        next.delete(cellId);
        return next;
      });
      setLoadingCellId(null);
    },
    (error, cellId) => {
      setCellErrors((prev) => {
        const next = new Map(prev);
        next.set(cellId, error.message);
        return next;
      });
      // Clear result on error
      setCellResults((prev) => {
        const next = new Map(prev);
        next.delete(cellId);
        return next;
      });
      setLoadingCellId(null);
      toast.error(error.message);
    },
  );

  const handleRunQuery = (
    cellId: number,
    query: string,
    datasourceId: string,
  ) => {
    console.log('handleRunQuery', cellId, query, datasourceId);
    const datasource = savedDatasources.data?.find(
      (ds) => ds.id === datasourceId,
    );
    if (!datasource) {
      toast.error('Datasource not found');
      return;
    }

    setLoadingCellId(cellId);
    telemetry.trackEvent(NOTEBOOK_EVENTS.NOTEBOOK_RUN_QUERY, {
      query,
      datasourceName: datasource.name,
    });
    runQueryMutation.mutate({
      cellId,
      query,
      datasourceId,
      datasource,
    });
  };

  // Run query with agent mutation
  const runQueryWithAgentMutation = useRunQueryWithAgent(
    (sqlQuery, cellId, datasourceId) => {
      // Agent generated SQL successfully, now run it
      handleRunQuery(cellId, sqlQuery, datasourceId);
    },
    (error, cellId, query) => {
      setCellErrors((prev) => {
        const next = new Map(prev);
        next.set(
          cellId,
          `${error.message} 
          sqlQuery: ${query}`,
        );
        return next;
      });
      // Clear result on error
      setCellResults((prev) => {
        const next = new Map(prev);
        next.delete(cellId);
        return next;
      });
      setLoadingCellId(null);
    },
  );

  const handleRunQueryWithAgent = (
    cellId: number,
    query: string,
    datasourceId: string,
  ) => {
    setLoadingCellId(cellId);
    telemetry.trackEvent(NOTEBOOK_EVENTS.NOTEBOOK_RUN_QUERY, {
      query,
      datasourceName: datasourceId,
    });
    runQueryWithAgentMutation.mutate({
      cellId,
      query,
      datasourceId,
      datasourceRepository,
    });
  };

  // Handle cells change - save notebook
  const handleCellsChange = useCallback(
    (cells: NotebookCellData[]) => {
      const now = new Date();
      const notebookData: Notebook = {
        id: notebook?.data?.id || uuidv4(),
        projectId: notebook?.data?.projectId || '',
        title: notebook?.data?.title || 'Untitled Notebook',
        description: notebook?.data?.description || '',
        slug: notebook?.data?.slug || '', // Will be auto-generated by repository
        version: notebook?.data?.version || 1,
        createdAt: notebook?.data?.createdAt || now,
        updatedAt: now,
        datasources:
          notebook?.data?.datasources ||
          savedDatasources.data?.map((ds) => ds.id) ||
          [],
        cells: cells.map((cell) => ({
          query: cell.query,
          cellType: cell.cellType,
          cellId: cell.cellId,
          datasources: cell.datasources,
          isActive: cell.isActive ?? true,
          runMode: cell.runMode ?? 'default',
        })),
      };

      saveNotebookMutation.mutate(notebookData);
    },
    [notebook, savedDatasources, saveNotebookMutation],
  );

  // Handle notebook change - save notebook
  const handleNotebookChange = useCallback(
    (changes: Partial<Notebook>) => {
      if (!notebook) return;

      const updatedNotebook: Notebook = {
        ...notebook?.data,
        ...changes,
        updatedAt: new Date(),
      } as Notebook;

      saveNotebookMutation.mutate(updatedNotebook);
    },
    [notebook, saveNotebookMutation],
  );

  // Map datasources to the format expected by NotebookUI
  const datasources = savedDatasources.data?.map((ds) => ({
    id: ds.id,
    name: ds.name,
  }));

  // Create loading states map
  const cellLoadingStates = new Map<number, boolean>();
  if (loadingCellId !== null) {
    cellLoadingStates.set(
      loadingCellId,
      runQueryMutation.isPending || runQueryWithAgentMutation.isPending,
    );
  }

  // Convert NotebookUseCaseDto to Notebook format
  const notebookData = notebook.data
    ? {
        ...notebook.data,
        cells: notebook.data.cells.map((cell) => ({
          ...cell,
          datasources: cell.datasources || [],
          cellType: cell.cellType || 'text',
          cellId: cell.cellId || 0,
          isActive: cell.isActive ?? true,
          runMode: cell.runMode || 'default',
        })),
      }
    : undefined;

  return (
    <>
      {notebook.isLoading && <Skeleton className="h-full w-full" />}
      {notebook.isError && <Navigate to="/404" />}
      {notebookData && (
        <NotebookUI
          notebook={notebookData}
          datasources={datasources}
          onRunQuery={handleRunQuery}
          onCellsChange={handleCellsChange}
          onNotebookChange={handleNotebookChange}
          onRunQueryWithAgent={handleRunQueryWithAgent}
          cellResults={cellResults}
          cellErrors={cellErrors}
          cellLoadingStates={cellLoadingStates}
        />
      )}
    </>
  );
}
