// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/version": {
    params: {};
  };
  "/healthcheck": {
    params: {};
  };
  "/qwery/*": {
    params: {
      "*": string;
    };
  };
  "/api/chat/:slug": {
    params: {
      "slug": string;
    };
  };
  "/api/organizations": {
    params: {};
  };
  "/api/organizations/:id": {
    params: {
      "id": string;
    };
  };
  "/api/projects": {
    params: {};
  };
  "/api/projects/:id": {
    params: {
      "id": string;
    };
  };
  "/api/datasources/:id?": {
    params: {
      "id"?: string;
    };
  };
  "/api/driver/command": {
    params: {};
  };
  "/api/extensions/registry": {
    params: {};
  };
  "/api/notebooks": {
    params: {};
  };
  "/api/notebooks/:id": {
    params: {
      "id": string;
    };
  };
  "/api/conversations": {
    params: {};
  };
  "/api/conversations/:id": {
    params: {
      "id": string;
    };
  };
  "/api/messages": {
    params: {};
  };
  "/api/usage": {
    params: {};
  };
  "/organizations": {
    params: {};
  };
  "/org/:slug": {
    params: {
      "slug": string;
    };
  };
  "/prj/:slug": {
    params: {
      "slug": string;
    };
  };
  "/notebook/:slug": {
    params: {
      "slug": string;
    };
  };
  "/prj/:slug/ds": {
    params: {
      "slug": string;
    };
  };
  "/prj/:slug/ds/new": {
    params: {
      "slug": string;
    };
  };
  "/prj/:slug/ds/:id/new": {
    params: {
      "slug": string;
      "id": string;
    };
  };
  "/prj/:slug/playground": {
    params: {
      "slug": string;
    };
  };
  "/prj/:slug/c": {
    params: {
      "slug": string;
    };
  };
  "/c/:slug": {
    params: {
      "slug": string;
    };
  };
  "/ds/:slug": {
    params: {
      "slug": string;
    };
  };
  "/ds/:slug/tables": {
    params: {
      "slug": string;
    };
  };
  "/ds/:slug/schema": {
    params: {
      "slug": string;
    };
  };
  "/ds/:slug/settings": {
    params: {
      "slug": string;
    };
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/version" | "/healthcheck" | "/qwery/*" | "/api/chat/:slug" | "/api/organizations" | "/api/organizations/:id" | "/api/projects" | "/api/projects/:id" | "/api/datasources/:id?" | "/api/driver/command" | "/api/extensions/registry" | "/api/notebooks" | "/api/notebooks/:id" | "/api/conversations" | "/api/conversations/:id" | "/api/messages" | "/api/usage" | "/organizations" | "/org/:slug" | "/prj/:slug" | "/notebook/:slug" | "/prj/:slug/ds" | "/prj/:slug/ds/new" | "/prj/:slug/ds/:id/new" | "/prj/:slug/playground" | "/prj/:slug/c" | "/c/:slug" | "/ds/:slug" | "/ds/:slug/tables" | "/ds/:slug/schema" | "/ds/:slug/settings";
  };
  "routes/version.ts": {
    id: "routes/version";
    page: "/version";
  };
  "routes/healthcheck.ts": {
    id: "routes/healthcheck";
    page: "/healthcheck";
  };
  "routes/ingest.$.ts": {
    id: "routes/ingest.$";
    page: "/qwery/*";
  };
  "routes/api/chat.ts": {
    id: "routes/api/chat";
    page: "/api/chat/:slug";
  };
  "routes/api/organization/get-all-organizations.ts": {
    id: "routes/api/organization/get-all-organizations";
    page: "/api/organizations";
  };
  "routes/api/organization/organization.ts": {
    id: "routes/api/organization/organization";
    page: "/api/organizations/:id";
  };
  "routes/api/project/get-all-projects.ts": {
    id: "routes/api/project/get-all-projects";
    page: "/api/projects";
  };
  "routes/api/project/project.ts": {
    id: "routes/api/project/project";
    page: "/api/projects/:id";
  };
  "routes/api/datasource/datasource.ts": {
    id: "routes/api/datasource/datasource";
    page: "/api/datasources/:id?";
  };
  "routes/api/driver/command.ts": {
    id: "routes/api/driver/command";
    page: "/api/driver/command";
  };
  "routes/api/extensions/registry.ts": {
    id: "routes/api/extensions/registry";
    page: "/api/extensions/registry";
  };
  "routes/api/notebook/get-all-notebooks.ts": {
    id: "routes/api/notebook/get-all-notebooks";
    page: "/api/notebooks";
  };
  "routes/api/notebook/notebook.ts": {
    id: "routes/api/notebook/notebook";
    page: "/api/notebooks/:id";
  };
  "routes/api/conversation/get-all-conversations.ts": {
    id: "routes/api/conversation/get-all-conversations";
    page: "/api/conversations";
  };
  "routes/api/conversation/conversation.ts": {
    id: "routes/api/conversation/conversation";
    page: "/api/conversations/:id";
  };
  "routes/api/conversation/get-messages.ts": {
    id: "routes/api/conversation/get-messages";
    page: "/api/messages";
  };
  "routes/api/usage/usage.ts": {
    id: "routes/api/usage/usage";
    page: "/api/usage";
  };
  "routes/layout/layout.tsx": {
    id: "routes/layout/layout";
    page: "/";
  };
  "routes/index.tsx": {
    id: "routes/index";
    page: "/";
  };
  "routes/organizations/layout.tsx": {
    id: "routes/organizations/layout";
    page: "/organizations";
  };
  "routes/organizations/index.tsx": {
    id: "routes/organizations/index";
    page: "/organizations";
  };
  "routes/organization/layout.tsx": {
    id: "routes/organization/layout";
    page: "/org/:slug";
  };
  "routes/organization/index.tsx": {
    id: "routes/organization/index";
    page: "/org/:slug";
  };
  "routes/project/layout.tsx": {
    id: "routes/project/layout";
    page: "/prj/:slug" | "/notebook/:slug" | "/prj/:slug/ds" | "/prj/:slug/ds/new" | "/prj/:slug/ds/:id/new" | "/prj/:slug/playground" | "/prj/:slug/c" | "/c/:slug";
  };
  "routes/project/index.tsx": {
    id: "routes/project/index";
    page: "/prj/:slug";
  };
  "routes/project/notebook.tsx": {
    id: "routes/project/notebook";
    page: "/notebook/:slug";
  };
  "routes/project/datasources/index.tsx": {
    id: "routes/project/datasources/index";
    page: "/prj/:slug/ds";
  };
  "routes/project/datasources/sources.tsx": {
    id: "routes/project/datasources/sources";
    page: "/prj/:slug/ds/new";
  };
  "routes/project/datasources/new.tsx": {
    id: "routes/project/datasources/new";
    page: "/prj/:slug/ds/:id/new";
  };
  "routes/project/playground.tsx": {
    id: "routes/project/playground";
    page: "/prj/:slug/playground";
  };
  "routes/project/conversation/index.tsx": {
    id: "routes/project/conversation/index";
    page: "/prj/:slug/c";
  };
  "routes/project/conversation/conversation.tsx": {
    id: "routes/project/conversation/conversation";
    page: "/c/:slug";
  };
  "routes/datasource/layout.tsx": {
    id: "routes/datasource/layout";
    page: "/ds/:slug" | "/ds/:slug/tables" | "/ds/:slug/schema" | "/ds/:slug/settings";
  };
  "routes/datasource/index.tsx": {
    id: "routes/datasource/index";
    page: "/ds/:slug";
  };
  "routes/datasource/tables.tsx": {
    id: "routes/datasource/tables";
    page: "/ds/:slug/tables";
  };
  "routes/datasource/schema.tsx": {
    id: "routes/datasource/schema";
    page: "/ds/:slug/schema";
  };
  "routes/datasource/settings.tsx": {
    id: "routes/datasource/settings";
    page: "/ds/:slug/settings";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.tsx");
  "routes/version": typeof import("./app/routes/version.ts");
  "routes/healthcheck": typeof import("./app/routes/healthcheck.ts");
  "routes/ingest.$": typeof import("./app/routes/ingest.$.ts");
  "routes/api/chat": typeof import("./app/routes/api/chat.ts");
  "routes/api/organization/get-all-organizations": typeof import("./app/routes/api/organization/get-all-organizations.ts");
  "routes/api/organization/organization": typeof import("./app/routes/api/organization/organization.ts");
  "routes/api/project/get-all-projects": typeof import("./app/routes/api/project/get-all-projects.ts");
  "routes/api/project/project": typeof import("./app/routes/api/project/project.ts");
  "routes/api/datasource/datasource": typeof import("./app/routes/api/datasource/datasource.ts");
  "routes/api/driver/command": typeof import("./app/routes/api/driver/command.ts");
  "routes/api/extensions/registry": typeof import("./app/routes/api/extensions/registry.ts");
  "routes/api/notebook/get-all-notebooks": typeof import("./app/routes/api/notebook/get-all-notebooks.ts");
  "routes/api/notebook/notebook": typeof import("./app/routes/api/notebook/notebook.ts");
  "routes/api/conversation/get-all-conversations": typeof import("./app/routes/api/conversation/get-all-conversations.ts");
  "routes/api/conversation/conversation": typeof import("./app/routes/api/conversation/conversation.ts");
  "routes/api/conversation/get-messages": typeof import("./app/routes/api/conversation/get-messages.ts");
  "routes/api/usage/usage": typeof import("./app/routes/api/usage/usage.ts");
  "routes/layout/layout": typeof import("./app/routes/layout/layout.tsx");
  "routes/index": typeof import("./app/routes/index.tsx");
  "routes/organizations/layout": typeof import("./app/routes/organizations/layout.tsx");
  "routes/organizations/index": typeof import("./app/routes/organizations/index.tsx");
  "routes/organization/layout": typeof import("./app/routes/organization/layout.tsx");
  "routes/organization/index": typeof import("./app/routes/organization/index.tsx");
  "routes/project/layout": typeof import("./app/routes/project/layout.tsx");
  "routes/project/index": typeof import("./app/routes/project/index.tsx");
  "routes/project/notebook": typeof import("./app/routes/project/notebook.tsx");
  "routes/project/datasources/index": typeof import("./app/routes/project/datasources/index.tsx");
  "routes/project/datasources/sources": typeof import("./app/routes/project/datasources/sources.tsx");
  "routes/project/datasources/new": typeof import("./app/routes/project/datasources/new.tsx");
  "routes/project/playground": typeof import("./app/routes/project/playground.tsx");
  "routes/project/conversation/index": typeof import("./app/routes/project/conversation/index.tsx");
  "routes/project/conversation/conversation": typeof import("./app/routes/project/conversation/conversation.tsx");
  "routes/datasource/layout": typeof import("./app/routes/datasource/layout.tsx");
  "routes/datasource/index": typeof import("./app/routes/datasource/index.tsx");
  "routes/datasource/tables": typeof import("./app/routes/datasource/tables.tsx");
  "routes/datasource/schema": typeof import("./app/routes/datasource/schema.tsx");
  "routes/datasource/settings": typeof import("./app/routes/datasource/settings.tsx");
};